insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (1, '66963 Scott Parkway', 'apt. K6', 'Brooklyn', 'NY', '11205');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (2, '512 Katie Road', 'apt. R573', 'Miami', 'FL', '33175');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (3, '4681 Bonner Plaza', 'suite 77', 'Charlotte', 'NC', '28210');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (4, '96 Farwell Circle', null, 'Washington', 'DC', '20010');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (5, '55 Jackson Center', null, 'Columbus', 'OH', '43284');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (6, '53 Commercial Circle', 'apt. L0', 'Bronx', 'NY', '10474');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (7, '627 Spenser Center', 'suite 9283', 'Lynchburg', 'VA', '24515');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (8, '50819 John Wall Circle', null, 'Norman', 'OK', '73071');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (9, '11357 Mifflin Point', null, 'Pocatello', 'ID', '83206');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (10, '88671 Golf Park', null, 'Maple Plain', 'MN', '55572');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (11, '45267 Toban Avenue', null, 'Albuquerque', 'NM', '87121');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (12, '7998 Fairview Circle', 'suite 54', 'Albany', 'NY', '12247');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (13, '6 Montana Parkway', null, 'Saint Louis', 'MO', '63180');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (14, '97 Dovetail Avenue', null, 'San Bernardino', 'CA', '92410');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (15, '8004 1st Trail', null, 'San Francisco', 'CA', '94169');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (16, '0727 Village Green Parkway', null, 'Yakima', 'WA', '98907');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (17, '77108 Elka Street', 'apt. Q596', 'Greeley', 'CO', '80638');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (18, '7846 Coolidge Place', null, 'Milwaukee', 'WI', '53225');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (19, '190 High Crossing Circle', null, 'Saint Paul', 'MN', '55166');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (20, '4 Maywood Park', null, 'Jamaica', 'NY', '11480');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (21, '377 Parkside Center', null, 'Canton', 'OH', '44705');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (22, '8 2nd Road', null, 'Midland', 'TX', '79710');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (23, '811 John Wall Lane', 'apt. S971', 'Fort Pierce', 'FL', '34981');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (24, '5 Garrison Place', null, 'Oklahoma City', 'OK', '73124');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (25, '70 Clemons Place', null, 'Lexington', 'KY', '40515');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (26, '54 Susan Trail', null, 'Flint', 'MI', '48555');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (27, '15 Ohio Alley', null, 'Tulsa', 'OK', '74108');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (28, '9 Badeau Pass', null, 'Baton Rouge', 'LA', '70826');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (29, '6 Gina Trail', null, 'Tulsa', 'OK', '74133');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (30, '797 Kedzie Junction', null, 'New Haven', 'CT', '06505');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (31, '88 Fuller Point', null, 'Sacramento', 'CA', '94230');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (32, '89620 Bellgrove Terrace', null, 'Johnson City', 'TN', '37605');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (33, '169 Banding Park', null, 'Fredericksburg', 'VA', '22405');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (34, '0071 Goodland Center', null, 'San Jose', 'CA', '95160');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (35, '808 Del Sol Place', 'suite 43', 'Anniston', 'AL', '36205');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (36, '68 Gina Trail', null, 'Aiken', 'SC', '29805');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (37, '9 Artisan Circle', null, 'Bradenton', 'FL', '34210');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (38, '23659 Hermina Lane', 'suite 2563', 'Washington', 'DC', '20073');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (39, '52388 Waywood Avenue', 'suite 2342', 'Tallahassee', 'FL', '32399');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (40, '41570 Comanche Plaza', null, 'Raleigh', 'NC', '27658');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (41, '45235 Kim Alley', null, 'Tampa', 'FL', '33625');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (42, '16 Little Fleur Trail', null, 'Honolulu', 'HI', '96815');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (43, '47682 Springs Park', null, 'New Haven', 'CT', '06510');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (44, '4565 Delaware Way', null, 'Louisville', 'KY', '40256');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (45, '5005 Monument Pass', null, 'Las Vegas', 'NV', '89155');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (46, '92167 Waubesa Plaza', null, 'Pasadena', 'TX', '77505');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (47, '3760 Columbus Center', null, 'Long Beach', 'CA', '90840');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (48, '6 Farragut Trail', 'suite 8460', 'Spokane', 'WA', '99215');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (49, '6 Crest Line Drive', 'apt. F24', 'Buffalo', 'NY', '14263');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (50, '91 Chinook Drive', null, 'Fresno', 'CA', '93726');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (51, '3 Pankratz Trail', null, 'Fort Lauderdale', 'FL', '33305');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (52, '6011 Hintze Road', null, 'Knoxville', 'TN', '37931');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (53, '3 Barnett Alley', null, 'Henderson', 'NV', '89074');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (54, '3 Little Fleur Trail', null, 'Young America', 'MN', '55573');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (55, '79048 6th Avenue', null, 'Durham', 'NC', '27710');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (56, '4 Stone Corner Drive', null, 'Bethlehem', 'PA', '18018');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (57, '0699 Elmside Place', null, 'Houston', 'TX', '77260');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (58, '93825 Packers Point', 'suite 17', 'Gainesville', 'FL', '32610');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (59, '6039 Graedel Junction', null, 'El Paso', 'TX', '88569');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (60, '6845 Luster Junction', null, 'Fort Lauderdale', 'FL', '33345');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (61, '76 Sycamore Park', null, 'Hartford', 'CT', '06105');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (62, '95803 Erie Trail', null, 'Hot Springs National Park', 'AR', '71914');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (63, '9986 Vahlen Lane', 'suite 3651', 'Richmond', 'VA', '23242');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (64, '8 Cambridge Court', 'apt. X1', 'New York City', 'NY', '10155');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (65, '7 Larry Circle', null, 'Columbia', 'SC', '29220');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (66, '642 Jackson Street', 'suite 199', 'Sacramento', 'CA', '94257');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (67, '34 Victoria Plaza', null, 'Amarillo', 'TX', '79182');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (68, '936 Anhalt Drive', null, 'Aiken', 'SC', '29805');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (69, '713 Loomis Trail', null, 'Tacoma', 'WA', '98481');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (70, '4 Lakewood Lane', null, 'Des Moines', 'IA', '50315');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (71, '7781 Buhler Court', null, 'Sacramento', 'CA', '95823');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (72, '44 Scott Road', 'apt. S123', 'Young America', 'MN', '55564');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (73, '55 Almo Trail', null, 'Albuquerque', 'NM', '87201');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (74, '1 Manitowish Junction', null, 'Norfolk', 'VA', '23514');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (75, '84 Kennedy Lane', null, 'Atlanta', 'GA', '30356');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (76, '660 Victoria Crossing', null, 'Lansing', 'MI', '48912');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (77, '2286 Melvin Court', null, 'Huntington', 'WV', '25711');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (78, '1 Old Shore Lane', null, 'Philadelphia', 'PA', '19104');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (79, '1 Buhler Court', null, 'Springfield', 'IL', '62718');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (80, '169 Crowley Way', null, 'Philadelphia', 'PA', '19178');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (81, '59 Forest Run Park', null, 'Chattanooga', 'TN', '37410');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (82, '37 Rieder Court', null, 'San Diego', 'CA', '92153');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (83, '944 Northfield Way', null, 'Boca Raton', 'FL', '33487');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (84, '779 Stephen Trail', null, 'Springfield', 'IL', '62711');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (85, '9 Haas Street', null, 'Mobile', 'AL', '36610');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (86, '0960 Mockingbird Road', 'suite 251', 'Dulles', 'VA', '20189');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (87, '9 Schurz Terrace', 'suite 38', 'Providence', 'RI', '02905');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (88, '35 Birchwood Terrace', null, 'Fresno', 'CA', '93762');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (89, '85 Iowa Road', null, 'Sacramento', 'CA', '95813');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (90, '7426 Del Mar Terrace', null, 'Philadelphia', 'PA', '19151');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (91, '210 Fordem Court', null, 'Sandy', 'UT', '84093');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (92, '05718 Oxford Trail', null, 'Pueblo', 'CO', '81010');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (93, '7741 Eastwood Avenue', 'suite 6513', 'Worcester', 'MA', '01654');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (94, '31 Bartillon Way', null, 'Topeka', 'KS', '66617');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (95, '99 Monica Park', 'suite 883', 'Charlotte', 'NC', '28299');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (96, '32 New Castle Trail', null, 'Los Angeles', 'CA', '90020');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (97, '77 Saint Paul Drive', null, 'Sioux Falls', 'SD', '57198');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (98, '9 Jenna Trail', 'suite 2542', 'Lansing', 'MI', '48956');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (99, '218 Shopko Junction', null, 'Baton Rouge', 'LA', '70836');
insert into addresses (id, addressLine1, addressLine2, city, state, zip) values (100, '22762 Hauk Street', null, 'Kansas City', 'MO', '64193');
