insert into publishers (id, name) values (1, 'MacGyver, Towne and Cormier');
insert into publishers (id, name) values (2, 'Bailey Inc');
insert into publishers (id, name) values (3, 'Zemlak Inc');
insert into publishers (id, name) values (4, 'Medhurst-Crist');
insert into publishers (id, name) values (5, 'Feil LLC');
insert into publishers (id, name) values (6, 'Grant-Effertz');
insert into publishers (id, name) values (7, 'Cummings, Schaefer and Kuhlman');
insert into publishers (id, name) values (8, 'Balistreri, Miller and Mayert');
insert into publishers (id, name) values (9, 'Nicolas Group');
insert into publishers (id, name) values (10, 'Strosin-Marquardt');
insert into publishers (id, name) values (11, 'Kilback, Schimmel and Thiel');
insert into publishers (id, name) values (12, 'Hane Inc');
insert into publishers (id, name) values (13, 'Lebsack, Purdy and Wisoky');
insert into publishers (id, name) values (14, 'Will LLC');
insert into publishers (id, name) values (15, 'Wolf and Sons');
insert into publishers (id, name) values (16, 'Bernier-Kuhlman');
insert into publishers (id, name) values (17, 'Parisian, Boehm and Langworth');
insert into publishers (id, name) values (18, 'Gislason-Streich');
insert into publishers (id, name) values (19, 'Mueller, O''Connell and Hettinger');
insert into publishers (id, name) values (20, 'Feil Group');
insert into publishers (id, name) values (21, 'Balistreri-Runte');
insert into publishers (id, name) values (22, 'Dare-Volkman');
insert into publishers (id, name) values (23, 'Gutmann, O''Keefe and Hegmann');
insert into publishers (id, name) values (24, 'Blick, Rosenbaum and Considine');
insert into publishers (id, name) values (25, 'O''Keefe, Gutkowski and Schimmel');
insert into publishers (id, name) values (26, 'Gislason, Gutkowski and Rippin');
insert into publishers (id, name) values (27, 'Borer LLC');
insert into publishers (id, name) values (28, 'Rosenbaum-Tromp');
insert into publishers (id, name) values (29, 'Walter-Mayer');
insert into publishers (id, name) values (30, 'Kertzmann, Batz and Lemke');
insert into publishers (id, name) values (31, 'Dietrich-Kunze');
insert into publishers (id, name) values (32, 'Mayer LLC');
insert into publishers (id, name) values (33, 'Williamson, Nienow and Armstrong');
insert into publishers (id, name) values (34, 'Rohan, Fahey and Haag');
insert into publishers (id, name) values (35, 'Borer Group');
insert into publishers (id, name) values (36, 'Miller-Halvorson');
insert into publishers (id, name) values (37, 'Gottlieb, Hartmann and Ankunding');
insert into publishers (id, name) values (38, 'Daniel-Johnston');
insert into publishers (id, name) values (39, 'Schiller-Cummerata');
insert into publishers (id, name) values (40, 'Grant-Shields');
insert into publishers (id, name) values (41, 'Shields-Mills');
insert into publishers (id, name) values (42, 'DuBuque, Kshlerin and Gaylord');
insert into publishers (id, name) values (43, 'Kihn, Langworth and Lebsack');
insert into publishers (id, name) values (44, 'Ernser, Wiegand and Kshlerin');
insert into publishers (id, name) values (45, 'Fahey-Wintheiser');
insert into publishers (id, name) values (46, 'Johnston LLC');
insert into publishers (id, name) values (47, 'Langosh, McClure and Koepp');
insert into publishers (id, name) values (48, 'Bruen and Sons');
insert into publishers (id, name) values (49, 'Johnson, Von and Jerde');
insert into publishers (id, name) values (50, 'Hegmann Group');
insert into publishers (id, name) values (51, 'Rowe, Schmeler and Reinger');
insert into publishers (id, name) values (52, 'Erdman-Shields');
insert into publishers (id, name) values (53, 'Ledner LLC');
insert into publishers (id, name) values (54, 'Dietrich, Welch and Schroeder');
insert into publishers (id, name) values (55, 'Keebler Group');
insert into publishers (id, name) values (56, 'Abshire-Abbott');
insert into publishers (id, name) values (57, 'Turner-Stracke');
insert into publishers (id, name) values (58, 'Waters, Walker and Schowalter');
insert into publishers (id, name) values (59, 'Satterfield-Cole');
insert into publishers (id, name) values (60, 'Hirthe-Konopelski');
insert into publishers (id, name) values (61, 'Smitham Group');
insert into publishers (id, name) values (62, 'Kautzer-Schamberger');
insert into publishers (id, name) values (63, 'Gottlieb-Johnston');
insert into publishers (id, name) values (64, 'Hintz and Sons');
insert into publishers (id, name) values (65, 'Langosh LLC');
insert into publishers (id, name) values (66, 'Mertz, Johns and Gorczany');
insert into publishers (id, name) values (67, 'Mante LLC');
insert into publishers (id, name) values (68, 'Sanford Group');
insert into publishers (id, name) values (69, 'Rohan-Friesen');
insert into publishers (id, name) values (70, 'Rogahn LLC');
insert into publishers (id, name) values (71, 'Marks, Torphy and Ziemann');
insert into publishers (id, name) values (72, 'Donnelly, Haag and Little');
insert into publishers (id, name) values (73, 'Metz, Thompson and Weimann');
insert into publishers (id, name) values (74, 'Feeney-Langosh');
insert into publishers (id, name) values (75, 'Price, Krajcik and Dicki');
insert into publishers (id, name) values (76, 'Emmerich, MacGyver and Beahan');
insert into publishers (id, name) values (77, 'Kihn Group');
insert into publishers (id, name) values (78, 'Fisher Inc');
insert into publishers (id, name) values (79, 'Lang and Sons');
insert into publishers (id, name) values (80, 'Bode-Cassin');
insert into publishers (id, name) values (81, 'Emard, Thiel and Wolff');
insert into publishers (id, name) values (82, 'Willms LLC');
insert into publishers (id, name) values (83, 'Wisoky, Turner and Auer');
insert into publishers (id, name) values (84, 'Murphy, Streich and Dickens');
insert into publishers (id, name) values (85, 'Sawayn Inc');
insert into publishers (id, name) values (86, 'Bartoletti, D''Amore and Botsford');
insert into publishers (id, name) values (87, 'Davis-VonRueden');
insert into publishers (id, name) values (88, 'Gibson, Graham and Streich');
insert into publishers (id, name) values (89, 'Lakin LLC');
insert into publishers (id, name) values (90, 'Price Group');
insert into publishers (id, name) values (91, 'Reinger-Hauck');
insert into publishers (id, name) values (92, 'Rohan and Sons');
insert into publishers (id, name) values (93, 'Rau LLC');
insert into publishers (id, name) values (94, 'Labadie, Ryan and Smith');
insert into publishers (id, name) values (95, 'Greenholt-Murphy');
insert into publishers (id, name) values (96, 'Morissette Group');
insert into publishers (id, name) values (97, 'Lang, Johns and McClure');
insert into publishers (id, name) values (98, 'Ruecker LLC');
insert into publishers (id, name) values (99, 'Williamson and Sons');
insert into publishers (id, name) values (100, 'Hahn and Sons');
