/*
-- Query: SELECT * FROM bookcountry.publishers
LIMIT 0, 1000

-- Date: 2017-04-23 20:49
*/
INSERT INTO `publishers` (`id`,`name`) VALUES (56,'Abshire-Abbott');
INSERT INTO `publishers` (`id`,`name`) VALUES (2,'Bailey Inc');
INSERT INTO `publishers` (`id`,`name`) VALUES (8,'Balistreri, Miller and Mayert');
INSERT INTO `publishers` (`id`,`name`) VALUES (21,'Balistreri-Runte');
INSERT INTO `publishers` (`id`,`name`) VALUES (86,'Bartoletti, D\'Amore and Botsford');
INSERT INTO `publishers` (`id`,`name`) VALUES (16,'Bernier-Kuhlman');
INSERT INTO `publishers` (`id`,`name`) VALUES (24,'Blick, Rosenbaum and Considine');
INSERT INTO `publishers` (`id`,`name`) VALUES (80,'Bode-Cassin');
INSERT INTO `publishers` (`id`,`name`) VALUES (35,'Borer Group');
INSERT INTO `publishers` (`id`,`name`) VALUES (27,'Borer LLC');
INSERT INTO `publishers` (`id`,`name`) VALUES (48,'Bruen and Sons');
INSERT INTO `publishers` (`id`,`name`) VALUES (7,'Cummings, Schaefer and Kuhlman');
INSERT INTO `publishers` (`id`,`name`) VALUES (38,'Daniel-Johnston');
INSERT INTO `publishers` (`id`,`name`) VALUES (22,'Dare-Volkman');
INSERT INTO `publishers` (`id`,`name`) VALUES (87,'Davis-VonRueden');
INSERT INTO `publishers` (`id`,`name`) VALUES (54,'Dietrich, Welch and Schroeder');
INSERT INTO `publishers` (`id`,`name`) VALUES (31,'Dietrich-Kunze');
INSERT INTO `publishers` (`id`,`name`) VALUES (72,'Donnelly, Haag and Little');
INSERT INTO `publishers` (`id`,`name`) VALUES (42,'DuBuque, Kshlerin and Gaylord');
INSERT INTO `publishers` (`id`,`name`) VALUES (81,'Emard, Thiel and Wolff');
INSERT INTO `publishers` (`id`,`name`) VALUES (76,'Emmerich, MacGyver and Beahan');
INSERT INTO `publishers` (`id`,`name`) VALUES (52,'Erdman-Shields');
INSERT INTO `publishers` (`id`,`name`) VALUES (44,'Ernser, Wiegand and Kshlerin');
INSERT INTO `publishers` (`id`,`name`) VALUES (45,'Fahey-Wintheiser');
INSERT INTO `publishers` (`id`,`name`) VALUES (74,'Feeney-Langosh');
INSERT INTO `publishers` (`id`,`name`) VALUES (20,'Feil Group');
INSERT INTO `publishers` (`id`,`name`) VALUES (5,'Feil LLC');
INSERT INTO `publishers` (`id`,`name`) VALUES (78,'Fisher Inc');
INSERT INTO `publishers` (`id`,`name`) VALUES (88,'Gibson, Graham and Streich');
INSERT INTO `publishers` (`id`,`name`) VALUES (26,'Gislason, Gutkowski and Rippin');
INSERT INTO `publishers` (`id`,`name`) VALUES (18,'Gislason-Streich');
INSERT INTO `publishers` (`id`,`name`) VALUES (37,'Gottlieb, Hartmann and Ankunding');
INSERT INTO `publishers` (`id`,`name`) VALUES (63,'Gottlieb-Johnston');
INSERT INTO `publishers` (`id`,`name`) VALUES (6,'Grant-Effertz');
INSERT INTO `publishers` (`id`,`name`) VALUES (40,'Grant-Shields');
INSERT INTO `publishers` (`id`,`name`) VALUES (95,'Greenholt-Murphy');
INSERT INTO `publishers` (`id`,`name`) VALUES (23,'Gutmann, O\'Keefe and Hegmann');
INSERT INTO `publishers` (`id`,`name`) VALUES (100,'Hahn and Sons');
INSERT INTO `publishers` (`id`,`name`) VALUES (12,'Hane Inc');
INSERT INTO `publishers` (`id`,`name`) VALUES (50,'Hegmann Group');
INSERT INTO `publishers` (`id`,`name`) VALUES (64,'Hintz and Sons');
INSERT INTO `publishers` (`id`,`name`) VALUES (60,'Hirthe-Konopelski');
INSERT INTO `publishers` (`id`,`name`) VALUES (49,'Johnson, Von and Jerde');
INSERT INTO `publishers` (`id`,`name`) VALUES (46,'Johnston LLC');
INSERT INTO `publishers` (`id`,`name`) VALUES (62,'Kautzer-Schamberger');
INSERT INTO `publishers` (`id`,`name`) VALUES (55,'Keebler Group');
INSERT INTO `publishers` (`id`,`name`) VALUES (30,'Kertzmann, Batz and Lemke');
INSERT INTO `publishers` (`id`,`name`) VALUES (77,'Kihn Group');
INSERT INTO `publishers` (`id`,`name`) VALUES (43,'Kihn, Langworth and Lebsack');
INSERT INTO `publishers` (`id`,`name`) VALUES (11,'Kilback, Schimmel and Thiel');
INSERT INTO `publishers` (`id`,`name`) VALUES (94,'Labadie, Ryan and Smith');
INSERT INTO `publishers` (`id`,`name`) VALUES (89,'Lakin LLC');
INSERT INTO `publishers` (`id`,`name`) VALUES (79,'Lang and Sons');
INSERT INTO `publishers` (`id`,`name`) VALUES (97,'Lang, Johns and McClure');
INSERT INTO `publishers` (`id`,`name`) VALUES (65,'Langosh LLC');
INSERT INTO `publishers` (`id`,`name`) VALUES (47,'Langosh, McClure and Koepp');
INSERT INTO `publishers` (`id`,`name`) VALUES (13,'Lebsack, Purdy and Wisoky');
INSERT INTO `publishers` (`id`,`name`) VALUES (53,'Ledner LLC');
INSERT INTO `publishers` (`id`,`name`) VALUES (1,'MacGyver, Towne and Cormier');
INSERT INTO `publishers` (`id`,`name`) VALUES (67,'Mante LLC');
INSERT INTO `publishers` (`id`,`name`) VALUES (71,'Marks, Torphy and Ziemann');
INSERT INTO `publishers` (`id`,`name`) VALUES (32,'Mayer LLC');
INSERT INTO `publishers` (`id`,`name`) VALUES (4,'Medhurst-Crist');
INSERT INTO `publishers` (`id`,`name`) VALUES (66,'Mertz, Johns and Gorczany');
INSERT INTO `publishers` (`id`,`name`) VALUES (73,'Metz, Thompson and Weimann');
INSERT INTO `publishers` (`id`,`name`) VALUES (36,'Miller-Halvorson');
INSERT INTO `publishers` (`id`,`name`) VALUES (96,'Morissette Group');
INSERT INTO `publishers` (`id`,`name`) VALUES (19,'Mueller, O\'Connell and Hettinger');
INSERT INTO `publishers` (`id`,`name`) VALUES (84,'Murphy, Streich and Dickens');
INSERT INTO `publishers` (`id`,`name`) VALUES (9,'Nicolas Group');
INSERT INTO `publishers` (`id`,`name`) VALUES (25,'O\'Keefe, Gutkowski and Schimmel');
INSERT INTO `publishers` (`id`,`name`) VALUES (17,'Parisian, Boehm and Langworth');
INSERT INTO `publishers` (`id`,`name`) VALUES (90,'Price Group');
INSERT INTO `publishers` (`id`,`name`) VALUES (75,'Price, Krajcik and Dicki');
INSERT INTO `publishers` (`id`,`name`) VALUES (93,'Rau LLC');
INSERT INTO `publishers` (`id`,`name`) VALUES (91,'Reinger-Hauck');
INSERT INTO `publishers` (`id`,`name`) VALUES (70,'Rogahn LLC');
INSERT INTO `publishers` (`id`,`name`) VALUES (92,'Rohan and Sons');
INSERT INTO `publishers` (`id`,`name`) VALUES (34,'Rohan, Fahey and Haag');
INSERT INTO `publishers` (`id`,`name`) VALUES (69,'Rohan-Friesen');
INSERT INTO `publishers` (`id`,`name`) VALUES (28,'Rosenbaum-Tromp');
INSERT INTO `publishers` (`id`,`name`) VALUES (51,'Rowe, Schmeler and Reinger');
INSERT INTO `publishers` (`id`,`name`) VALUES (98,'Ruecker LLC');
INSERT INTO `publishers` (`id`,`name`) VALUES (68,'Sanford Group');
INSERT INTO `publishers` (`id`,`name`) VALUES (59,'Satterfield-Cole');
INSERT INTO `publishers` (`id`,`name`) VALUES (85,'Sawayn Inc');
INSERT INTO `publishers` (`id`,`name`) VALUES (39,'Schiller-Cummerata');
INSERT INTO `publishers` (`id`,`name`) VALUES (41,'Shields-Mills');
INSERT INTO `publishers` (`id`,`name`) VALUES (61,'Smitham Group');
INSERT INTO `publishers` (`id`,`name`) VALUES (10,'Strosin-Marquardt');
INSERT INTO `publishers` (`id`,`name`) VALUES (57,'Turner-Stracke');
INSERT INTO `publishers` (`id`,`name`) VALUES (29,'Walter-Mayer');
INSERT INTO `publishers` (`id`,`name`) VALUES (58,'Waters, Walker and Schowalter');
INSERT INTO `publishers` (`id`,`name`) VALUES (14,'Will LLC');
INSERT INTO `publishers` (`id`,`name`) VALUES (99,'Williamson and Sons');
INSERT INTO `publishers` (`id`,`name`) VALUES (33,'Williamson, Nienow and Armstrong');
INSERT INTO `publishers` (`id`,`name`) VALUES (82,'Willms LLC');
INSERT INTO `publishers` (`id`,`name`) VALUES (83,'Wisoky, Turner and Auer');
INSERT INTO `publishers` (`id`,`name`) VALUES (15,'Wolf and Sons');
INSERT INTO `publishers` (`id`,`name`) VALUES (3,'Zemlak Inc');
