/*
-- Query: select * from languages
LIMIT 0, 1000

-- Date: 2017-04-20 00:11
*/
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (1,'aar','Afar');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (2,'abk','Abkhaz');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (3,'ave','Avestan');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (4,'afr','Afrikaans');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (5,'aka','Akan');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (6,'amh','Amharic');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (7,'arg','Aragonese');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (8,'ara','Arabic');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (9,'asm','Assamese');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (10,'ava','Avaric');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (11,'aym','Aymara');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (12,'aze','Azerbaijani');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (13,'azb','South Azerbaijani');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (14,'bak','Bashkir');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (15,'bel','Belarusian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (16,'bul','Bulgarian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (17,'bih','Bihari');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (18,'bis','Bislama');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (19,'bam','Bambara');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (20,'ben','Bengali; Bangla');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (21,'tib','Tibetan Standard');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (22,'bre','Breton');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (23,'bos','Bosnian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (24,'cat','Catalan; Valencian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (25,'che','Chechen');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (26,'cha','Chamorro');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (27,'cos','Corsican');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (28,'cre','Cree');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (29,'cze','Czech');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (30,'chu','Old Church Slavonic');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (31,'chv','Chuvash');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (32,'wel','Welsh');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (33,'dan','Danish');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (34,'ger','German');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (35,'div','Divehi; Dhivehi; Maldivian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (36,'dzo','Dzongkha');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (37,'ewe','Ewe');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (38,'gre','Greek');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (39,'eng','English');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (40,'epo','Esperanto');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (41,'spa','Spanish; Castilian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (42,'est','Estonian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (43,'baq','Basque');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (44,'per','Persian (Farsi)');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (45,'ful','Fula; Fulah; Pulaar; Pular');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (46,'fin','Finnish');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (47,'fij','Fijian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (48,'fao','Faroese');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (49,'fre','French');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (50,'fry','Western Frisian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (51,'gle','Irish');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (52,'gla','Scottish Gaelic; Gaelic');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (53,'glg','Galician');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (54,'grn','Guarani');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (55,'guj','Gujarati');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (56,'glv','Manx');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (57,'hau','Hausa');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (58,'heb','Hebrew');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (59,'hin','Hindi');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (60,'hmo','Hiri Motu');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (61,'hrv','Croatian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (62,'hat','Haitian; Haitian Creole');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (63,'hun','Hungarian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (64,'arm','Armenian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (65,'her','Herero');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (66,'ina','Interlingua');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (67,'ind','Indonesian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (68,'ile','Interlingue');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (69,'ibo','Igbo');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (70,'iii','Nuosu');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (71,'ipk','Inupiaq');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (72,'ido','Ido');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (73,'ice','Icelandic');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (74,'ita','Italian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (75,'iku','Inuktitut');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (76,'jpn','Japanese');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (77,'jav','Javanese');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (78,'geo','Georgian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (79,'kon','Kongo');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (80,'kik','Kikuyu');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (81,'kua','Kwanyama');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (82,'kaz','Kazakh ');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (83,'kal','Kalaallisut');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (84,'khm','Khmer');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (85,'kan','Kannada');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (86,'kor','Korean');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (87,'kau','Kanuri');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (88,'kas','Kashmiri');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (89,'kur','Kurdish');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (90,'kom','Komi');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (91,'cor','Cornish');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (92,'kir','Kyrgyz');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (93,'lat','Latin');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (94,'ltz','Luxembourgish');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (95,'lug','Ganda');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (96,'lim','Limburgish');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (97,'lin','Lingala');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (98,'lao','Lao');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (99,'lit','Lithuanian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (100,'lub','Luba-Katanga');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (101,'lav','Latvian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (102,'mlg','Malagasy');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (103,'mah','Marshallese');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (104,'mao','Māori');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (105,'mac','Macedonian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (106,'mal','Malayalam');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (107,'mon','Mongolian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (108,'mar','Marathi');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (109,'may','Malay');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (110,'mlt','Maltese');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (111,'bur','Burmese');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (112,'nau','Nauru');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (113,'nob','Norwegian Bokmal');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (114,'nde','North Ndebele');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (115,'nep','Nepali');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (116,'ndo','Ndonga');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (117,'dut','Dutch');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (118,'nno','Norwegian Nynorsk');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (119,'nor','Norwegian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (120,'nbl','South Ndebele');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (121,'nav','Navajo');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (122,'nya','Chichewa; Chewa; Nyanja');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (123,'oci','Occitan');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (124,'oji','Ojibwe');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (125,'orm','Oromo');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (126,'ori','Oriya');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (127,'oss','Ossetian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (128,'pan','Panjabi');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (129,'pli','Pāli');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (130,'pol','Polish');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (131,'pus','Pashto');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (132,'por','Portuguese');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (133,'que','Quechua');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (134,'roh','Romansh');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (135,'run','Kirundi');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (136,'rum','Romanian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (137,'rus','Russian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (138,'kin','Kinyarwanda');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (139,'san','Sanskrit');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (140,'srd','Sardinian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (141,'snd','Sindhi');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (142,'sme','Northern Sami');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (143,'sag','Sango');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (144,'sin','Sinhala');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (145,'slo','Slovak');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (146,'slv','Slovene');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (147,'smo','Samoan');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (148,'sna','Shona');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (149,'som','Somali');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (150,'alb','Albanian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (151,'srp','Serbian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (152,'ssw','Swati');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (153,'sot','Southern Sotho');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (154,'sun','Sundanese');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (155,'swe','Swedish');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (156,'swa','Swahili');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (157,'tam','Tamil');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (158,'tel','Telugu');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (159,'tgk','Tajik');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (160,'tha','Thai');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (161,'tir','Tigrinya');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (162,'tuk','Turkmen');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (163,'tgl','Tagalog');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (164,'tsn','Tswana');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (165,'ton','Tonga (Tonga Islands)');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (166,'tur','Turkish');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (167,'tso','Tsonga');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (168,'tat','Tatar');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (169,'twi','Twi');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (170,'tah','Tahitian');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (171,'uig','Uyghur');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (172,'ukr','Ukrainian ');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (173,'urd','Urdu');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (174,'uzb','Uzbek');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (175,'ven','Venda');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (176,'vie','Vietnamese');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (177,'vol','Volapuk');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (178,'wln','Walloon');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (179,'wol','Wolof');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (180,'xho','Xhosa');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (181,'yid','Yiddish');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (182,'yor','Yoruba');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (183,'zha','Zhuang');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (184,'chi','Chinese');
INSERT INTO `languages` (`id`,`code`,`name`) VALUES (185,'zul','Zulu');
